services:
  # Symfony API
  nginx:
    image: nginx:1.25-alpine
    container_name: rezerwuj_nginx
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/symfony
      - ./api/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  
  php:
    build:
      context: ./api
      dockerfile: docker/php/Dockerfile
    container_name: rezerwuj_php
    volumes:
      - ./api:/var/www/symfony
    environment:
      - APP_ENV=dev
      - APP_SECRET=a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6
      - DATABASE_URL=postgresql://app_user:app_password@db:5432/app_db?serverVersion=16&charset=utf8
      - MESSENGER_TRANSPORT_DSN=redis://redis:6379/messages
      - CORS_ALLOW_ORIGIN=^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    container_name: rezerwuj_db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: rezerwuj_redis
    ports:
      - "6379:6379"

  # React Frontend
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: rezerwuj_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    environment:
      - VITE_API_BASE_URL=http://localhost:8080

volumes:
  db_data:
